### ISSUE TITLE
Have roxbot deal with dependabot updates

### ISSUE THREAD

**Issue by RTann** [stackrox/go-grpc-http1#183]
Manually handling dependabot updates is annoying, and we tend to just blindly accept the updates anyway. Perhaps we should consider adding roxbot to this repo and having it take care of it for us. Thoughts @stackrox/maple ?

**Comment by vikin91** [comment]
Yes, that makes sense to add a bot to do that. However, we do not accept fully blindly the updates, I guess, we all check whether CI is happy.
How can we onboard the bot to auto merge dependabot PRs that pass the CI?

**Comment by Maddosaurus** [comment]
Hmm. Maybe we can check in with @janisz, as he just introduced auto-retest for our own PRs. Maybe he has an idea?
https://redhat-internal.slack.com/archives/CELUQKESC/p1711124692089649

**Comment by janisz** [comment]
To auto-merge dependabot PR's just add this action and it should handle that. 
https://github.com/stackrox/jenkins-plugin/blob/master/.github/workflows/auto-merge.yml
```
name: auto-merge

on:
  pull_request_target:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
    - uses: ahmadnassri/action-dependabot-auto-merge@v2.6
      with:
        github-token: '${{ secrets.RHACS_BOT_GITHUB_TOKEN }}'
        command: "squash and merge"
        approve: true
        target: minor
 ```
